name: fliper
description: Test project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  graphql: ^4.0.1
  provider: ^4.3.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/imgs/contact.jpg

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 100
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 200
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 500
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 600
